### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by deejf** [GITenberg/The-Iron-Trail_5233#1]
The text seems to be truncated in chapter XIX (19), at line 8965 in the text file. The remainder of the paragraph and at least one further paragraph appear to be missing, perhaps more than that.

> "We can't build the S. R.

The thought is not completed, and the rest of the dialogue makes clear there was a response that was also missed.

I'm trying to track down page images to see if I can replace/correct the error. The only possible source I've found initially is a [PDF from Google](https://books.google.com/books/about/The_iron_trail.html?id=7YchAAAAMAAJ&hl=en), which I will check for that passage later.

**Comment by deejf** [comment]
Wow. Five paragraphs missing, **plus** the remainder of the one quoted. No wonder the scene felt jumpy!

I've never done a GitHub change before, but hopefully it's as easy as it sounds. I'll do a fork, add the missing text, and then do a "pull request".

**Comment by eshellman** [comment]
wow!

**Comment by sethwoodworth** [comment]
Thank you for discovering this issue and tracking down the solution!

How did you come upon this issue?  It is awfully far into the work.  I'm trying to collect information for others who would like to participate.
If you're interested, we also have a [mailing list](https://groups.google.com/forum/#!forum/gitenberg-project) for the project.

**Comment by deejf** [comment]
You're quite welcome.

How did I come upon this issue? Easy: I'm [reading it](https://www.goodreads.com/review/show/1282693393), and tripped over the issue last night. It was recommended to me as the sort of thing I would like for a number of reasons (western genre, concerned with economics and construction, a few other things that are up my alley), both this title and the author's work in general, and I was taking a reading break from other things.

I do believe I'm already on the mailing list, but will double check. I've got so many plates spinning that I lose track of things until the interest in one hits strongly again. ^___^

Out of curiosity, I notice the epub is not included here. Is that part of the future mission of GITenberg, to re-do auto-generated epubs? Because I have to say, while the Gutenberg-generated one is readable, when I opened it up in Sigil, I rolled up my sleeves and started changing things to my liking. (Why not break each chapter into a separate file, e.g., instead of randomly doing it in the middle of some chapters? Why not have the CSS format the text to look like a printed book, instead of putting a line of space between paragraphs like a web page? That kind of thing.)

Anyway, my corrected fork and the pull request are up. If there is anything I missed that I should have done, let me know, as I'm new to GitHub.

**Comment by sethwoodworth** [comment]
Yes! We will be creating epubs on github.  We were working out some issues with our build system, but I've built a number of [epubs](https://github.com/sethwoodworth/nyplcodex/blob/master/final.asciidoc) in my personal forks.  But these will make their way into the Gitenberg repos soon.

**Comment by eshellman** [comment]
Two things worth noting (and adding issues to gitenberg-dev)
1. We need to document that ebook files are created on a tag, and what is our workflow for creating a tag?
2. We need to implement ebook-creation from html (old method) and work out how to do asciidoc forks.

**Comment by deejf** [comment]
OK, I've poked around a bit and have another question that (I'm sure) is answered at length somewhere I haven't found yet.

Why is the conversion standard going to be asciidoc rather than Markdown? I tinker with creating epubs of public domain books not on Gutenberg's lists, and transcribing to Markdown, then converting that to HTML and epub has been the easiest process I've found. Though at this point, I'm unfamiliar with asciidoc, so possibly I just am ignorant of the advantages. On the other hand, I do all my own writing in Markdown, so I'm definitely prejudiced toward it. ^___^

(I'm going to read up on asciidoc a bit today or tomorrow, when I can.)

**Comment by eshellman** [comment]
Seth promised to write something about that, specifically, but, you know, coding doesn't do itself.

The short explanation is this:  If you look at Leanpub, Gitbook, etc, you can see how a Markdown-based toolchain would play out. Great as far as it goes, but then you have to add stuff. Then the road becomes unclear. Starting from Markdown would require us to invent more stuff.

We need at least 2 backends already - in addition to asciidoc, we need a backend to handle the hand-coded html in PG. People have talked about alternate paths for TEI and for LaTeX. It's just coding. The markdown/asciidoc usage cases strongly overlap; who knows maybe one of the markdown sites will contribute code.

Eric

**Comment by eshellman** [comment]
Note to self: add this as an issue in gitenberg-dev/documentation

**Comment by deejf** [comment]
>  ...coding doesn't do itself.

Easy enough for non-programmers like me to forget. I honestly wasn't being snarky, I just wanted to know what the reasons were. My workflow from Markdown to epub does involve adding metadata at the epub stage, so I guess I should have thought of that.
